version: '3.3'
services:
  littlelemon:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'littlelemon'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'nedjme'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root@123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root@123'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_data:/var/lib/mysql
# Names our volume
volumes:
  db_data: