# Generated by Django 5.0.6 on 2024-07-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_of_guests',
            field=models.IntegerField(default=1),
        ),
    ]
